[package]
name = "bevy-demos"
version = "0.1.0"
authors = ["Darius Wiles <github@dariuswiles.com>"]
edition = "2021"

[dependencies]
bevy = { version = "0.7", features = ["dynamic"] }
fastrand = "1.7"
